### ISSUE TITLE
vocabulary builder 1.33 flatpak

### ISSUE THREAD

**Issue by fastrizwaan** [rorokimdim/stash-gui#1]
Hi Amit,

I was keeping your vocabjava program since 2006. Now made it a flatpak. Hope you like it.
https://github.com/fastrizwaan/vocabjava_flatpak

**Comment by rorokimdim** [comment]
wow I can't believe that stuff is still around. That was a long time ago and I'm surprised it works at all. Thanks @fastrizwaan
